# Generated by Django 5.0.3 on 2024-03-05 12:49

import django.db.models.deletion
import enumfields.fields
import payments.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=255, null=True, unique=True)),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('status', enumfields.fields.EnumField(default='created', enum=payments.enums.TransactionStatus, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', enumfields.fields.EnumField(enum=payments.enums.Currency, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
